-- AlterTable
ALTER TABLE "Car" ALTER COLUMN "colors" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "features" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "price" DROP NOT NULL,
ALTER COLUMN "availability" SET DEFAULT false,
ALTER COLUMN "images" SET DEFAULT ARRAY[]::TEXT[];
